### ISSUE TITLE
Question; How to control RGB LED Strip ?

### ISSUE THREAD

**Issue by offtherails2010** [tjclement/esp-dimmer-software#2]
Howdy and well done firstly, the 3 channel RGB controller PCB is SUPER AWESOME !!!!!!!!!!!!

BUT...

i cant see where or how to actually link to the ESP12 As its soldered to your module, what software on what cell phone, android, iphone, windows computer ?

Say once its soldered together, powered up correctly with the 3.3v in step 3 then how does one actually use the dimmer function, do you send commands to it via aq terminal ?

im desperately needing this to make an RGB LED strip To go on the back of my mum's TV as a nice colourful present for her,

So is this easy to control and how ?

i know this is an old project, but i truly hope you could reply, im loving SMD Soldering and looking forward to saving up the pennies to get all these parts ordered, but before i do, id love to know the answers to above question/s

Thanks so very much in advance,, you seriously ROCK DUDE !!!!!!!!!!!!!!!

Very clever project !!

**Comment by tjclement** [comment]
Thanks, good to see enthusiasm here.

You can put whatever software you want on the ESP. This repository contains some of the code I used in my home. 

If you've never worked with custom firmware before, I recommend something that is easier to use. I've heard good things about [ESP Easy](https://www.letscontrolit.com/wiki/index.php/ESPEasy). It has a web interface, and you can use it to control the channels that the dimmer module uses (GPIO 12, 13, and 14) via [the PWM command shown here](https://www.letscontrolit.com/wiki/index.php/GPIO#Commands).

**Comment by offtherails2010** [comment]
howdy Tom, thanks so very very much for the reply, i am very humbly grateful :)

i am indeed a beginner with ESP modules, im heartbroken at the sight of code though lol

i can solder upto 0402 SMD parts but i just cant get my head around how to write Code - even for simpler stuff like arduino code :(

too old to learn new tricks lol

i have tried and can edit code if detailed instructions are shown that i can follow, but i cant write my own.

So just wanted to say thank you immensely, i will start collecting these components now and willl try my very best to dig into those links you provided, im really after something really easy to control the ESP, so not only i can control it, say via cell phone, but also my mother who is an OAP & needs tech to be really clear and simple UI interface's lol

Your ingenuity really has amazed me and even though this is an old project, im so damn happy i stumbled upon it !!!

i LOVE Eagle, SMD Soldering and RGB Strip lights ! so my hats off to you for providing this slice of awesomeness to the masses and keeping it open source !

Also, lastly, i opened up the 3-channel PCB .brd and .sch files but Eagle reports that the board is inconsistent and has a load of problems,

would you please be able to take a look at the files and see them to check if they are correct by downloading them so i dont waste a month's wait from china for these boards to arrive ?

Again, major awesomeness long-distance hand-shake  from UK ! LOVE YOUR WORK !

my kind & best regards & wishes from Anil :)

**Comment by tjclement** [comment]
Hi Anil,

Thanks again. For extra user friendliness, you could run something like [Domoticz](http://domoticz.com) on a computer in your (mum's) home. They integrate nicely with ESP Easy, and have a web interface plus apps for mobile devices.

Eagle reports inconsistency because of some manual tweaks in the board design, and shows warnings for clearance of the ground plane polygons and stop masks. All of these are perfectly fine. I've ordered the modules made from this exact design, and they work as expected.

If you're unsure about generating gerber files yourself from within Eagle, you can also just use [the Gerber files I've prepared](https://github.com/tjclement/esp-dimmer-hardware/tree/master/triple_channel/gerber_files). If you'd like, you can also directly order the modules directly [from DirtyPCBs here](http://dirtypcbs.com/store/designer/details/tjclement/1329/5-esp8266-rgb-led-dimmer). If you choose to order from this link, I get a ~$1 credit with them for future projects.

When ordering RGB strips, be sure to get ones with the normal 4 wire design (+5 or 12V, R, G, B), not the pixel-addressable ones that have 3 wires.

Have fun!

**Comment by offtherails2010** [comment]
Youre very welcome Tom, my mother is going to be so pleased with that kind of setup via computer as im in the middle of upgrading mum's computer too, so she's going to be amazed at this lil add-on !

honestly, its like some kinda unknown sorcery magic this kinda stuff, for folk who dont know how things operate, like me poor mum lol gonna savour the look on her face when its sorted !

Once again, well done man, and thank you so very very much for keeping the design open source, i willl try to save up to buy from your link too, its just that im on such low income its ridiculous, so the next time i have any pennies to spend will be mid-april :( so unfair :(

Please keep up the awesome idea's coming, youve given me the motivation to get back involved with this tinkering business haha

when its complete i will also show my mum your pages here on github and say this was only possible because of you !!!!

apologies if the praise is a bit over the top, but honestly, people like you well-deserve it, nice one matey :))
